### ISSUE TITLE
EmitterMixin#_listeningTo should not be stringified.

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5-utils#114]
Anything that mixes `EmitterMixin` and listens to something, gets `_listeningTo` property. This is also true, of course, for `LiveRange`. Such `LiveRange`, when stringified to JSON, has that property. This is incorrect for `LiveRange` and will probably be incorrect for anything that uses `EmitterMixin`.

This needs to be fixed, and here are two approaches:

1. Specify `toJSON` for each class mixing `EmitterMixin`. In that custom `toJSON` remove `_listeningTo`. This is bad because we need to remember about it each time.
2. Make `_listeningTo` not enumerable. I think this is a better approach, especially since this is hidden, private property.

**Comment by Reinmar** [comment]
Yy... this should be a symbol of course. Everything which the EmitterMixin sets should be.

But that's not because of `JSON.stringify()` but just some safety (name clashes) and correctness. Classes like `LiveRange` should have their serialisers or overriden `toJSON` methods. E.g. the root property needs to be replaced when stringifying this class.

So, while I agree with this change, I think that you may be doing something odd :P

**Comment by scofalik** [comment]
It wasn't a symbol. I wonder why this is not a symbol (other than that `EmitterMixin` is one of the oldest parts of code). I guess this solution is worth checking too.

`LiveRange` should not need it's own `toJSON` method if it does not have any "difficult" properties. `Range` has `Position` instances and those have their `toJSON` methods (that handle `root` etc.).

**Comment by Reinmar** [comment]
You're right that it isn't a symbol because it's the oldest part of the code. Symbols are not iterable, so they shouldn't be in the JSON.

As for stringifying ranges I'm not totally ok with that, but it's not a big difference.

**Comment by scofalik** [comment]
I used Symbols and also fixed `_emitterId`.
