### ISSUE TITLE
Rect and scroll utilities should support multi window scenarios (aka iframe support)

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-utils#175]
See: 

* https://github.com/ckeditor/ckeditor5-utils/pull/174#discussion_r133238556
* https://github.com/ckeditor/ckeditor5-utils/pull/174#discussion_r133238226

**Comment by oleq** [comment]
This issue should get a higher priority since we use iframes in the documentation (red border). Upon changing the heading, `viewDocument.scrollToTheSelection` is called and it scrolls the entire web page despite the fact that the selection and heading are actually visible to the user. It's super-annoying.

![kapture 2017-09-08 at 10 55 39](https://user-images.githubusercontent.com/1099479/30204091-89ba2170-9484-11e7-9a5b-8f193043fd0f.gif)
