### ISSUE TITLE
Config#define and #get are not very useful for feature developers

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-utils#33]
Moved from https://github.com/ckeditor/ckeditor5/issues/148

**Comment by Reinmar** [comment]
I've just thought that the whole access through `config.foo.bar.bom` makes no sense if we want to throw errors from `config.get( 'foo.bar.bom' )`. Two ways of accessing values will be confusing so I would only allow `get()`.

**Comment by Reinmar** [comment]
And another thought: https://github.com/ckeditor/ckeditor5/issues/157

**Comment by oskarwrobel** [comment]
> I've just thought that the whole access through config.foo.bar.bom makes no sense if we want to throw > errors from config.get( 'foo.bar.bom' ). Two ways of accessing values will be confusing so I would only > allow get().

Access through `config.foo.bar.bom` is a "consequence" of using `observableMixin` inside `Config` implementation. I don't know what was the purpose of using this mixin, Should config be observable? Or It is only for reducing code and avoiding duplications? There is no test case which tests observable feature in `Config` test.

**Comment by Reinmar** [comment]
This is... totally broken AFAICS.

First of all, config is immutable, so there's no point at all in mixing `Observable` interface into it.

Second, depending on how you use `set()` it either makes only the top-most properties observable (by using `ObservableMixin.set()`) or does the totally different thing when you pass a `p.a.t.h` as a first argument, because then it creates a deep `Config`s structure.

Perhaps all this works in some reasonable way, but:

1. We had an issue... so it doesn't.
2. If I don't understand the code, it I can't analyse it.

At this point it looks like there's already a technical debt which I think we must remove, especially that we're touching the class anyway.

So we need a fresh and clean spec for it. I'll try to write one today.

**Comment by oskarwrobel** [comment]
**Configuration class specification:**

- Configuration class is a class to store `key => value` data where `value` could be any type. In case when value is an object, the value becomes a config subset.
Setting data is possible during class initialization by passing object with initial data set to the class constructor.
```
new Config( {
    lorem: 'impsum',
    foo: {
        bar: 'biz'
    }
} );
```
- Setting data is possible by a `set()` method where we can pass data as a name/value pair or an object (passing an object as the name or value will amend the configuration, not replace it). Set method also accepts setting "deep configuration" by using dots in the name. Eg.
```
const config = new Config();

// name/value pairs
config.set( 'lorem', 'ipsum' );
config.set( 'foo', {
    bar: 'biz'
} );

// object
config.set( {
    lorem: 'ipsum',
    foo: {
        bar: 'biz'
    }
} );

// deep configuration
config.set( 'some.structure', 'value' );
```
- Getting data is possible only by getting properties directly from the config object.
```
const config = new Config( {
    lorem: 'ipsum',
    foo: {
        bar: 'biz'
    }
} );

config.foo.bar; // returns 'biz'
```

**Comment by Reinmar** [comment]
Hm... let's think about the use cases, because AFAICS this class can be extremely simple.

1. Object with user settings comes to the `Editor()` constructor. The `editor.config` object needs to be initialized with it.
2. Afterwards, features can set the default values of options that weren't specified by the user.

That's all we need so far. Sounds like we need only this  `Config( userConfig )` and `Config#define( [path?], defaults )`.
