### ISSUE TITLE
Get rid of locale-mock#inject method

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-utils#72]
Tests coverage stats suggest that [this util](https://github.com/ckeditor/ckeditor5-utils/blob/master/tests/_utils/locale-mock.js#L21-L24) is not used anywhere in the entire codebase.  Whatever the reason, it's time to get rid of it to avoid dead code in master.

**Comment by Reinmar** [comment]
First we need to answer why it is not used any more.

**Comment by Reinmar** [comment]
Funny, but it turns out that this method has not been used since... forever. The reason we missed that was, most likely, that the whole file wasn't used anywhere so we didn't see it on CC.

Anyway, I guess you started using the locale mock just now. Could you show me where? Because that method may still be useful – it depends on what and how we test. We can remove it, but if we see that tomorrow we'll need it it's better to just write a test for it and keep it in mind.

PS. Don't forget about writing a test for the piece of locale-mock which is being used.

**Comment by oleq** [comment]
>  Could you show me where?

@oskarwrobel used it in https://github.com/ckeditor/ckeditor5-link/blob/t/2/tests/ui/linkballoonpanel.js#L17 but constructor only, not `inject()`.

**Comment by Reinmar** [comment]
I've got a feeling that the `inject()` method will be useful one day, but I guess we can remove it now, since we're only testing locale with UI.
